export const iols = [
    {
      name: {
        brand: 'Alcon',
        platform: 'PMMA',
        model: 'MTA3U0',
      },
      rangeStep: [5, 30, 1],
      constants: {
        nominal: 115.3,
        srkt: null,
        srk2: null,
        hoffer: null,
        holladay: null,
        haigis: null,
        barret: null,
      },
      length: {
        optic: 5.5,
        haptic: 7,
        total: 12.5,
      },
      material: ['PMMA'],
      type: 'Ant Chamber',
      productInfo: 'http://embed.widencdn.net/pdf/plus/alcon/djcplhttyy/10-500-086_us_en.pdf?u=4rqn9d',
      __v: 0,
    },
    {
      name: {
        brand: 'Alcon',
        platform: 'Test',
        model: 'MTA3U01',
      },
      rangeStep: [5, 30, 1],
      constants: {
        nominal: 115.3,
        srkt: null,
        srk2: null,
        hoffer: null,
        holladay: null,
        haigis: null,
        barret: null,
      },
      length: {
        optic: 5.5,
        haptic: 7,
        total: 12.5,
      },
      material: ['PMMA'],
      type: 'Single Piece',
      productInfo: 'http://embed.widencdn.net/pdf/plus/alcon/djcplhttyy/10-500-086_us_en.pdf?u=4rqn9d',
      __v: 0,
    },
    {
      name: {
        brand: 'Alcon',
        platform: 'Test',
        model: 'MTA3U012',
      },
      rangeStep: [5, 30, 1],
      constants: {
        nominal: 115.3,
        srkt: null,
        srk2: null,
        hoffer: null,
        holladay: null,
        haigis: null,
        barret: null,
      },
      length: {
        optic: 5.5,
        haptic: 7,
        total: 12.5,
      },
      material: ['PMMA'],
      type: '3 Piece',
      productInfo: 'http://embed.widencdn.net/pdf/plus/alcon/djcplhttyy/10-500-086_us_en.pdf?u=4rqn9d',
      __v: 0,
    },
    {
      name: {
        brand: 'Zeiss',
        platform: 'Test',
        model: 'MTA3U012',
      },
      rangeStep: [5, 30, 1],
      constants: {
        nominal: 115.3,
        srkt: null,
        srk2: null,
        hoffer: null,
        holladay: null,
        haigis: null,
        barret: null,
      },
      length: {
        optic: 5.5,
        haptic: 7,
        total: 12.5,
      },
      material: ['PMMA'],
      type: 'Ant Chamber',
      productInfo: 'http://embed.widencdn.net/pdf/plus/alcon/djcplhttyy/10-500-086_us_en.pdf?u=4rqn9d',
      __v: 0,
    },
  ];
  